name: Bowdens
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: "http://www.bowdens.me"
twitter_username: bo_wd_en
github_username: bowdens
description: >-
  The personal website and blog of Tom Bowden

